### ISSUE TITLE
How to use live demo?

### ISSUE THREAD

**Issue by leanne1** [JoostKiens/react-spring-visualizer#27]
Hi Joost

Your visualizer sounds great. However, I don't see how to use the visualizer. When i go to the live demo i see a blank box (see screenshot) and as such clicking buttons and changing presets does nothing.  It is not clear to me rom the UI if this is a bug or if there is something else i need to do to use the visualizer. Could you please give some more info? Tried in Chrome 79 and Firefox latest on Mac OSX 10.14.6

Thanks!

<img width="1048" alt="Screenshot 2020-01-16 at 09 40 50" src="https://user-images.githubusercontent.com/8372298/72513002-92cc1000-3844-11ea-938e-539c24a9b7ce.png">

**Comment by JoostKiens** [comment]
Uo oh, that doesn't look like it's supposed to! Thanks for reporting this!
I know it doesn't help you, but on my OSX (10.15.2) with FireFox & Chrome it works fine.

So can you do me a favor & let me if know there are any errors or warming in your console (option+cmd+J in Chrome)?

**Comment by leanne1** [comment]
I tried again today and it's working correctly now! No console errors evident.

**Comment by JoostKiens** [comment]
Ah, glad to hear that!  A glitch in the matrix I assume.
